apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: notification-service
  type: ClusterIP