apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: product-service
  type: ClusterIP