apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: order-service
  type: ClusterIP