apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: shopping-cart-service
  type: ClusterIP