apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: payment-service
  type: ClusterIP